name: flutter_music
description: flutter music demo

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  fluro: ^1.5.1
  get_it: ^3.0.3
  cached_network_image: ^1.1.2+1
  provider: ^3.1.0+1
  netease_music_api:
    path: cloud_music_api/


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
